name: "Issue triage"
run-name: "Issue triage - #${{ github.event.issue.number }}: ${{ github.event.issue.title }} - ${{ github.actor }}"

on: issue_comment

defaults:
    run:
        shell: bash

permissions:
    issues: write

jobs:
    triage:
        if: contains(github.event.issue.labels.*.name, 'triage:awaiting-response')
        uses: dbt-labs/actions/.github/workflows/swap-labels.yml@main
        with:
            add_label: "triage:product"
            remove_label: "triage:awaiting-response"
        secrets: inherit
